const express=require('express');
const ruta=express.Router();
const controlleruser=require("../controllers/usuarioController");
const auth = require('../controllers/auth');
ruta.get('/',auth.verificatoken, controlleruser.listado);
ruta.post('/',auth.verificatoken,controlleruser.agregar);
ruta.put('/',auth.verificatoken,controlleruser.actualiza);
ruta.delete('/',auth.verificatoken,controlleruser.borrar);
ruta.post('/login',controlleruser.login);
module.exports = ruta;
