const express=require('express');
const ruta=express.Router();
const controlleruser=require("../controllers/usuarioController");
const auth = require('../controllers/auth');
ruta.get('/', controlleruser.listado);
ruta.post('/',controlleruser.agregar);
ruta.post('/',controlleruser.actualiza);
ruta.post('/borrar',controlleruser.borrar);
ruta.post('/login',controlleruser.login);
module.exports = ruta;
